// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stat.Models;

#nullable disable

namespace Stat.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250810110835_AddNumerateurAndDenominateurToDeclarations1")]
    partial class AddNumerateurAndDenominateurToDeclarations1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Stat.Models.CategorieIndicateur", b =>
                {
                    b.Property<string>("IdCategIn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IntituleCategIn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategIn");

                    b.ToTable("CategorieIndicateurs");
                });

            modelBuilder.Entity("Stat.Models.Cible", b =>
                {
                    b.Property<int>("id_cible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_cible"), 1L, 1);

                    b.Property<string>("CodeDIW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_cible");

                    b.ToTable("cibles");
                });

            modelBuilder.Entity("Stat.Models.DC", b =>
                {
                    b.Property<string>("CodeDC")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("LibelleDC")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CodeDC");

                    b.ToTable("DCs");
                });

            modelBuilder.Entity("Stat.Models.Declaration", b =>
                {
                    b.Property<int>("id_dec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_dec"), 1L, 1);

                    b.Property<double>("Denominateur")
                        .HasColumnType("float");

                    b.Property<string>("ID_User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Numerateur")
                        .HasColumnType("float");

                    b.Property<float?>("cible")
                        .HasColumnType("real");

                    b.Property<string>("codediw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("ecart")
                        .HasColumnType("real");

                    b.Property<int>("month")
                        .HasColumnType("int");

                    b.Property<float?>("taux")
                        .HasColumnType("real");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id_dec");

                    b.ToTable("Declarations");
                });

            modelBuilder.Entity("Stat.Models.DeclarationDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float?>("Cible")
                        .HasColumnType("real");

                    b.Property<double>("Denominateur")
                        .HasColumnType("float");

                    b.Property<float?>("Ecart")
                        .HasColumnType("real");

                    b.Property<string>("IDSituation")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Numerateur")
                        .HasColumnType("float");

                    b.Property<float?>("Taux")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("IDSituation");

                    b.ToTable("DeclarationDrafts");
                });

            modelBuilder.Entity("Stat.Models.DIW", b =>
                {
                    b.Property<string>("CodeDIW")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("CodeDRI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleDIW")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CodeDIW");

                    b.ToTable("DIWs");
                });

            modelBuilder.Entity("Stat.Models.DRI", b =>
                {
                    b.Property<string>("CodeDRI")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("LibelleDRI")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CodeDRI");

                    b.ToTable("DRIs");
                });

            modelBuilder.Entity("Stat.Models.Indicateur", b =>
                {
                    b.Property<string>("IdIn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdCategIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntituleIn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdIn");

                    b.ToTable("Indicateurs");
                });

            modelBuilder.Entity("Stat.Models.Situation", b =>
                {
                    b.Property<string>("IDSituation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ConfirmDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DIW")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.HasKey("IDSituation");

                    b.ToTable("Situations");
                });

            modelBuilder.Entity("Stat.Models.User", b =>
                {
                    b.Property<string>("ID_User")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodeDIW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateDeCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Fin_Affect")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_deb_Affect")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstNmUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("KeepLoggedIn")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCnx")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastNmUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MailUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("TelUser")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ID_User");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Stat.Models.ValeurCible", b =>
                {
                    b.Property<int>("IdValeurCible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdValeurCible"), 1L, 1);

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.Property<string>("IdIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mois")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Valeur")
                        .HasColumnType("real");

                    b.Property<decimal>("ValeurCibleMensuelle")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("ValeurCumulee")
                        .HasColumnType("real");

                    b.HasKey("IdValeurCible");

                    b.ToTable("ValeurCibles");
                });

            modelBuilder.Entity("Stat.Models.ValeurRealisé", b =>
                {
                    b.Property<string>("Idvalreal")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AnneeIn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DIW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MoisIn")
                        .HasColumnType("datetime2");

                    b.Property<float>("Valeur")
                        .HasColumnType("real");

                    b.HasKey("Idvalreal");

                    b.ToTable("ValeurRealisés");
                });

            modelBuilder.Entity("Stat.Models.DeclarationDraft", b =>
                {
                    b.HasOne("Stat.Models.Situation", "Situation")
                        .WithMany()
                        .HasForeignKey("IDSituation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Situation");
                });
#pragma warning restore 612, 618
        }
    }
}
